import type {
  ContactWorkflowRecord,
  DeadlineSourceChange,
  DocumentTemplate,
  RolePermission,
  TransactionDocument,
} from '@/types/domain';

export const PURCHASE_CONTRACT_DOCUMENTS = [
  'Contract to Buy and Sell Real Estate',
  'Earnest Money Receipt',
  'Counterproposal',
  'Amend / Extend Contract',
  'Notice to Terminate Contract',
  'Inspection Objection',
  'Inspection Resolution',
  'Appraisal Objection',
  'Appraisal Resolution',
  'Title Objection',
  'Title Resolution',
  'Due Diligence Documents',
  'Closing Instructions',
  'Additional Provisions Addendum',
  'Personal Property Agreement',
  'Seller Concessions Addendum',
  'Backup Contract Addendum',
  'Post-Closing Occupancy Agreement',
  'Agreement to Amend Deadline',
] as const;

export const DOCUMENT_STATUS_LABELS = {
  missing: 'Missing',
  uploaded: 'Uploaded',
  ready_for_review: 'Ready for Review',
  reviewed: 'Reviewed',
  approved: 'Approved',
  superseded: 'Superseded',
  rejected: 'Rejected',
} as const;

export const DOCUMENT_TEMPLATES: DocumentTemplate[] = PURCHASE_CONTRACT_DOCUMENTS.map((documentName, index) => ({
  id: `purchase-contract-${index + 1}`,
  sectionName: 'Purchase Contract Documents',
  documentName,
  sortOrder: index + 1,
  isRequiredByDefault: true,
  adminEditable: true,
  createdBy: 'brett-admin',
  updatedBy: 'brett-admin',
}));

export const WORKFLOW_PREVIEW_DOCUMENTS: TransactionDocument[] = [
  {
    id: 'td-contract',
    transactionId: 'tx-preview',
    templateId: 'purchase-contract-1',
    documentName: 'Contract to Buy and Sell Real Estate',
    sectionName: 'Purchase Contract Documents',
    neededState: 'needed',
    workflowStatus: 'approved',
    fileId: 'file-contract',
    fileName: 'CBS_2140_Pine_Ridge.pdf',
    uploadCount: 1,
    uploadedAt: '2026-05-28T16:30:00Z',
    uploadedBy: 'agent-1',
    reviewedAt: '2026-05-28T17:05:00Z',
    reviewedBy: 'brett-admin',
    approvedAt: '2026-05-28T17:10:00Z',
    approvedBy: 'Brett Predmore',
    sourceNotes: 'Current source for price, MEC, inspection, title, appraisal, and closing deadlines.',
  },
  {
    id: 'td-earnest',
    transactionId: 'tx-preview',
    templateId: 'purchase-contract-2',
    documentName: 'Earnest Money Receipt',
    sectionName: 'Purchase Contract Documents',
    neededState: 'needed',
    workflowStatus: 'ready_for_review',
    fileId: 'file-earnest',
    fileName: 'Earnest_Money_Receipt.pdf',
    uploadCount: 1,
    uploadedAt: '2026-05-29T10:15:00Z',
    uploadedBy: 'agent-1',
    sourceNotes: 'Awaiting Brett/admin review before completion counts update.',
  },
  {
    id: 'td-counter',
    transactionId: 'tx-preview',
    templateId: 'purchase-contract-3',
    documentName: 'Counterproposal',
    sectionName: 'Purchase Contract Documents',
    neededState: 'not_applicable',
    workflowStatus: 'missing',
    uploadCount: 0,
    sourceNotes: 'Marked N/A; excluded from required completion and client-facing noise.',
  },
  {
    id: 'td-amend-1',
    transactionId: 'tx-preview',
    templateId: 'purchase-contract-4',
    documentName: 'Amend / Extend Contract',
    sectionName: 'Purchase Contract Documents',
    neededState: 'needed',
    workflowStatus: 'approved',
    fileId: 'file-amend-1',
    fileName: 'Amend_Extend_1.pdf',
    uploadCount: 1,
    sequenceNumber: 1,
    uploadedAt: '2026-06-01T12:40:00Z',
    uploadedBy: 'agent-1',
    reviewedAt: '2026-06-01T13:15:00Z',
    reviewedBy: 'brett-admin',
    approvedAt: '2026-06-01T13:22:00Z',
    approvedBy: 'Brett Predmore',
    sourceNotes: 'Superseded original inspection objection date.',
  },
  {
    id: 'td-amend-2',
    transactionId: 'tx-preview',
    templateId: 'purchase-contract-4',
    documentName: 'Amend / Extend Contract',
    sectionName: 'Purchase Contract Documents',
    neededState: 'needed',
    workflowStatus: 'reviewed',
    fileId: 'file-amend-2',
    fileName: 'Amend_Extend_2.pdf',
    uploadCount: 2,
    sequenceNumber: 2,
    uploadedAt: '2026-06-04T09:05:00Z',
    uploadedBy: 'agent-1',
    reviewedAt: '2026-06-04T09:45:00Z',
    reviewedBy: 'brett-admin',
    supersedesDocumentId: 'td-amend-1',
    sourceNotes: 'Reviewed; approval will update deadline tracking with provenance.',
  },
];

export const DEADLINE_SOURCE_CHANGES: DeadlineSourceChange[] = [
  {
    id: 'dl-inspection-objection',
    transactionId: 'tx-preview',
    name: 'Inspection Objection Deadline',
    previousDate: '2026-06-07',
    date: '2026-06-12',
    sourceDocumentId: 'td-amend-2',
    sourceDocumentName: 'Amend / Extend #2',
    confidence: 0.93,
    reviewStatus: 'reviewed',
    uploadedDate: '2026-06-04',
    approvedBy: 'Brett Predmore',
  },
  {
    id: 'dl-closing',
    transactionId: 'tx-preview',
    name: 'Closing Date',
    previousDate: '2026-06-28',
    date: '2026-07-03',
    sourceDocumentId: 'td-amend-2',
    sourceDocumentName: 'Amend / Extend #2',
    confidence: 0.9,
    reviewStatus: 'pending',
    uploadedDate: '2026-06-04',
  },
];

export const ROLE_PERMISSIONS: RolePermission[] = [
  {
    role: 'admin',
    label: 'Brett / Admin',
    canUploadDocuments: true,
    canViewTransaction: true,
    canApproveExtraction: true,
    canApproveDeadlineUpdates: true,
    canArchiveTransactions: true,
    canDeleteTemplates: true,
    canGloballyEditTemplates: true,
    canReorderTemplates: true,
    canManageContacts: true,
  },
  {
    role: 'agent',
    label: 'Agent / Broker user',
    canUploadDocuments: true,
    canViewTransaction: true,
    canApproveExtraction: false,
    canApproveDeadlineUpdates: false,
    canArchiveTransactions: false,
    canDeleteTemplates: false,
    canGloballyEditTemplates: false,
    canReorderTemplates: false,
    canManageContacts: false,
  },
  {
    role: 'system',
    label: 'System suggestions',
    canUploadDocuments: false,
    canViewTransaction: false,
    canApproveExtraction: false,
    canApproveDeadlineUpdates: false,
    canArchiveTransactions: false,
    canDeleteTemplates: false,
    canGloballyEditTemplates: false,
    canReorderTemplates: false,
    canManageContacts: false,
  },
];

export const CONTACT_WORKFLOW_PREVIEW: ContactWorkflowRecord[] = [
  {
    id: 'contact-title',
    transactionId: 'tx-preview',
    contactType: 'vendor',
    name: 'Front Range Title',
    company: 'Front Range Title',
    role: 'Title company',
    email: 'closings@example.com',
    phone: '(719) 555-0142',
    isCustom: false,
    createdBy: 'brett-admin',
    adminOnlyDelete: true,
  },
  {
    id: 'contact-roof',
    transactionId: 'tx-preview',
    contactType: 'contractor',
    name: 'Peak Roof Repair',
    company: 'Peak Roof Repair',
    role: 'Custom contractor invoice',
    email: 'ops@example.com',
    phone: '(719) 555-0188',
    isCustom: true,
    createdBy: 'brett-admin',
    adminOnlyDelete: false,
  },
];
